Refactor GreenHouseController
pb-iot/simulator pull request #21
Opened 2024-01-03 12:27 UTC by Jaaaaaxi

2024-01-03 12:28 UTC, konrad121970 submitted a review, later dismissed
Wygląda okej

2024-01-03 16:36 UTC, ondreo requested changes
Jedna rzecz w kilku miejscach będzie do poprawki. Opisałem komentarz w kodzie.

2024-01-03 16:36 UTC, ondreo commented on src/main/java/com/example/simulator/controller/GreenhouseController.java
> -            @ApiResponse(responseCode = "400", description = "SIMULATION_OF_GIVEN_TYPE_DOES_NOT_EXIST"),
Czemu tu został usunięty kod błędu "400" zamiast tylko zrefactorować, jak w metodzie "addSimulation"?

Podobnie w pozostałych metodach (getSimulationValue, setAirConditioningValue, itd.), zniknęła deklaracja kodu błędu "400".

2024-01-06 23:13 UTC, ondreo approved these changes
Jeden drobny błąd zauważyłem, ale to już poprawiłem sam. Daję approve.

2024-01-06 23:30 UTC, konrad121970 approved these changes
Po poprawce Andrzeja jest pięknie

2024-01-06 23:40 UTC, merged

2024-01-06 23:40 UTC, ondreo commented
Zmerge'owałem pull requesta ✅