refactor simulator
pb-iot/simulator pull request #4
Opened 2023-10-11 10:54 UTC by julek64

2023-10-16 21:33 UTC, ondreo requested changes
Dodałem w kodzie kilka drobnych uwag, z czego jedna dotyczy stricte funkcjonalności symulacji temperatury - nie wiem czy jest to dobrze zrealizowane.

------------------------------------------------------------

Dobry pomysł z tym rodzieleniem czujników na interfejs i implementujące je poszczególne klasy 👍

------------------------------------------------------------

Inna sprawa:

Zastanawiam się, czy nie mieliśmy tak zrobić, że my mamy jedynie zwiększać lub zmniejszać temperaturę w zależności od tego, jaka informacja została nam podana (włączyć ogrzewanie lub wyłączyć), ale żeby to sam backend przechowywał żądaną temperaturę i on przetwarzał kiedy nam wysłać żądanie do zwiększenia/zmniejszenia temperatury.

Chodzi mi o to, że nasza aplikacja to ma być, jak rozumiem, sam symulator:
- czujników,
- urządzeń, które wpływają na zmianę odczytów czujników, np. zwiększenie/zmniejszenie temperatury,

a jakiekolwiek przetwarzanie mamy zostawić backendowi.

2023-10-16 21:33 UTC, ondreo commented on src/main/java/com/example/simulator/data/sensors/TemperatureSimulation.java
> +    @Getter
`@Getter` nie jest potrzebny nad polem, jak jest adnotacja `@Data` nad całą klasą.

2023-10-16 21:33 UTC, ondreo commented on src/main/java/com/example/simulator/data/sensors/TemperatureSimulation.java
> +    @Getter
j.w.

2023-10-16 21:33 UTC, ondreo commented on src/main/java/com/example/simulator/simulation/SimulatorService.java
> +import java.util.ArrayList;
Do usunięcia zbędne importy

2023-10-16 21:33 UTC, ondreo commented on src/main/java/com/example/simulator/data/sensors/TemperatureSimulation.java
> +        var delta = (deltaRaw * changeSpeed) + ((random.nextDouble() - .5) * randomizationValue);
Czy to na pewno działa? Z tego co widzę, jeśli:
- `targetValue = 25.0`,
- `simulatedValue = 20.0`,

to w pierwszej iteracji `deltaRaw` wyniesie `5.0`, natomiast
to delta będzie wynosić:
`(deltaRaw * changeSpeed) + ((random.nextDouble() - .5) * randomizationValue)`,
czyli
`(5 * 0.1) + (<-0.5, 0.5> * 2)`, gdzie `<-0.5, 0.5>` to liczba z przedziału od -0.5 do 0.5,
czyli
- maksymalnie: 0.5 + 0.5*2 = 0.5+1 = 1.5 --> temperatura wzrośnie o 1.5 stopnia Celsjusza ✅
- minimalnie: 0.5 + (-0.5)*2 = 0.5 - 1 = -0.5 --> temperatura zmaleje o 0.5 stopnia Celsjusza ❌

Jeśli będzie drugi przypadek, to w drugiej iteracji może być znowu spadek, tym razem o:
(5.5 * 0.1) + (-0.5 * 2) = 0.55 - 1 = -0.45

W kolejnych iteracjach znowu może być problem.

@julek64 prosiłbym o wyjaśnienie, bo może to źle zinterpretowałem, ale jak odpaliłem ten kod tych danych, to miałem taki wynik:
```
delta: 0.8545672708287955
simulatedValue: 20.9

delta: -0.06991377069321336
simulatedValue: 20.799999999999997

delta: 0.02560322663310649
simulatedValue: 20.799999999999997

delta: 0.24202988254822383
simulatedValue: 20.999999999999996

delta: -0.4393331512382177
simulatedValue: 20.599999999999998

delta: 1.2377208314545853
simulatedValue: 21.799999999999997

delta: -0.6101729864233831
simulatedValue: 21.199999999999996

delta: 0.3365032748234661
simulatedValue: 21.499999999999996

delta: -0.09601832594060816
simulatedValue: 21.399999999999995

delta: -0.6227941069884948
simulatedValue: 20.799999999999994
```
czyli widać, że temperatura raz rośnie, raz maleje, co raczej nie jest pożądanym efektem.

2023-10-17 05:54 UTC, julek64 commented
> Zastanawiam się, czy nie mieliśmy tak zrobić, że my mamy jedynie zwiększać lub zmniejszać temperaturę w zależności od tego, jaka informacja została nam podana (włączyć ogrzewanie lub wyłączyć), ale żeby to sam backend przechowywał żądaną temperaturę i on przetwarzał kiedy nam wysłać żądanie do zwiększenia/zmniejszenia temperatury.
> 
> Chodzi mi o to, że nasza aplikacja to ma być, jak rozumiem, sam symulator:
> 
>     * czujników,
> 
>     * urządzeń, które wpływają na zmianę odczytów czujników, np. zwiększenie/zmniejszenie temperatury,
> 
> 
> a jakiekolwiek przetwarzanie (np. dążenie do jakiejś konkretnej temperatury) mamy zostawić backendowi.
> 
> Tak to rozumiem, ale oczywiście może to źle zrozumiałem. Prosiłbym @julek64 o odpowiedź co o tym myślisz.

Ja kierowałem się tym że np. jak masz taką standardową klimatyzację, to w niej właśnie ustalasz wartość docelową i ta klima próbuję do niej dążyć. Tak jak teraz o tym myślę, to widzę dwa podejścia:
- to które zrobiłem, czyli symulujemy urządzenie ogrzewające, które ma jednocześnie możliwość czytania temperatury i manipulowania nią dążąc do target value (tak jak w klimie)
- takie, w którym mamy oddzielnie termometr i jakieś grzejniki; w tym przypadku możemy udostępnić enpoint który włącza/wyłącza ogrzewanie (z ewentualną siłą ogrzewania, coś w stylu mocno/bardzo mocno, ale bez stopni bo w tym przypadku nie miało by to sensu wg mnie); ale nawet w takim podejściu uważam że musimy mieć jakąś ukrytą zmienną która określa domyślną temperaturę (w sensie że jak ogrzewanie jest wyłączone, to do jakiej wartości temperatura będzie spadać)

Teraz myślę że ta druga opcja faktycznie jest lepsza, jeśli się zgodzisz @ondreo to poprawię to, nie powinno mi to zająć długo.

2023-10-18 10:40 UTC, ondreo commented
Z racji na nowego Pull Requesta (nr 5), ostatecznie będą merge'owane oba te pull requesty. Zostawiam tego Pull Requesta, bo nie wiem gdzie ostatecznie zmiany zostaną dodane.

2023-10-20 19:36 UTC, Monikaa1909 approved these changes

2023-10-24 09:27 UTC, ondreo commented
Pull requesty #4 (ten) i #5 są merge'owane w ramach pull requesta #8, zatem zamykam tego pull requesta.

2023-10-24 09:27 UTC, closed without merging